/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Outfit {
    items: Array<bigint>;
}
export interface WardrobeItem {
    color: string;
    productId?: bigint;
    customName?: string;
    category: string;
}
export interface TrendItem {
    trendTags: Array<string>;
    productId: bigint;
    trendScore: bigint;
    dateAdded: bigint;
}
export interface StyleProfile {
    bodyMeasurements: BodyMeasurements;
    savedOutfits: Array<Outfit>;
    userId: Principal;
    trendAlerts: Array<string>;
    stylePreferences: Array<string>;
}
export interface Product {
    id: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    imageUrl: string;
    category: string;
    colors: Array<string>;
    price: bigint;
    isTrending: boolean;
}
export interface BodyMeasurements {
    weight: bigint;
    height: bigint;
    hips: bigint;
    chest: bigint;
    waist: bigint;
}
export interface backendInterface {
    addProduct(product: Product): Promise<void>;
    addTrendItem(trend: TrendItem): Promise<void>;
    addWardrobeItem(userId: Principal, item: WardrobeItem): Promise<void>;
    createOrUpdateStyleProfile(profile: StyleProfile): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getPersonalizedTrends(userId: Principal): Promise<Array<TrendItem>>;
    getProductById(id: bigint): Promise<Product>;
    getProductsByCategory(category: string): Promise<Array<Product>>;
    getStyleProfile(userId: Principal): Promise<StyleProfile>;
    getTrendingItems(): Promise<Array<TrendItem>>;
    getWardrobe(userId: Principal): Promise<Array<WardrobeItem>>;
    getWardrobeSuggestions(userId: Principal): Promise<Array<Product>>;
    removeSavedOutfit(userId: Principal, index: bigint): Promise<void>;
    removeWardrobeItem(userId: Principal, index: bigint): Promise<void>;
    saveOutfit(userId: Principal, outfit: Outfit): Promise<void>;
    searchProducts(queryString: string): Promise<Array<Product>>;
    seedProducts(): Promise<void>;
    seedTrendItems(): Promise<void>;
}
import type { WardrobeItem as _WardrobeItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async addTrendItem(arg0: TrendItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrendItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrendItem(arg0);
            return result;
        }
    }
    async addWardrobeItem(arg0: Principal, arg1: WardrobeItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWardrobeItem(arg0, to_candid_WardrobeItem_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWardrobeItem(arg0, to_candid_WardrobeItem_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateStyleProfile(arg0: StyleProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateStyleProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateStyleProfile(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getPersonalizedTrends(arg0: Principal): Promise<Array<TrendItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalizedTrends(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalizedTrends(arg0);
            return result;
        }
    }
    async getProductById(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return result;
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return result;
        }
    }
    async getStyleProfile(arg0: Principal): Promise<StyleProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStyleProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStyleProfile(arg0);
            return result;
        }
    }
    async getTrendingItems(): Promise<Array<TrendItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingItems();
            return result;
        }
    }
    async getWardrobe(arg0: Principal): Promise<Array<WardrobeItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWardrobe(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWardrobe(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWardrobeSuggestions(arg0: Principal): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWardrobeSuggestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWardrobeSuggestions(arg0);
            return result;
        }
    }
    async removeSavedOutfit(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSavedOutfit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSavedOutfit(arg0, arg1);
            return result;
        }
    }
    async removeWardrobeItem(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWardrobeItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWardrobeItem(arg0, arg1);
            return result;
        }
    }
    async saveOutfit(arg0: Principal, arg1: Outfit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOutfit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOutfit(arg0, arg1);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return result;
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async seedTrendItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedTrendItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedTrendItems();
            return result;
        }
    }
}
function from_candid_WardrobeItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WardrobeItem): WardrobeItem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: string;
    productId: [] | [bigint];
    customName: [] | [string];
    category: string;
}): {
    color: string;
    productId?: bigint;
    customName?: string;
    category: string;
} {
    return {
        color: value.color,
        productId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.productId)),
        customName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.customName)),
        category: value.category
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WardrobeItem>): Array<WardrobeItem> {
    return value.map((x)=>from_candid_WardrobeItem_n4(_uploadFile, _downloadFile, x));
}
function to_candid_WardrobeItem_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WardrobeItem): _WardrobeItem {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: string;
    productId?: bigint;
    customName?: string;
    category: string;
}): {
    color: string;
    productId: [] | [bigint];
    customName: [] | [string];
    category: string;
} {
    return {
        color: value.color,
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        customName: value.customName ? candid_some(value.customName) : candid_none(),
        category: value.category
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
