/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const TrendItem = IDL.Record({
  'trendTags' : IDL.Vec(IDL.Text),
  'productId' : IDL.Nat,
  'trendScore' : IDL.Nat,
  'dateAdded' : IDL.Int,
});
export const WardrobeItem = IDL.Record({
  'color' : IDL.Text,
  'productId' : IDL.Opt(IDL.Nat),
  'customName' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const BodyMeasurements = IDL.Record({
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'hips' : IDL.Nat,
  'chest' : IDL.Nat,
  'waist' : IDL.Nat,
});
export const Outfit = IDL.Record({ 'items' : IDL.Vec(IDL.Nat) });
export const StyleProfile = IDL.Record({
  'bodyMeasurements' : BodyMeasurements,
  'savedOutfits' : IDL.Vec(Outfit),
  'userId' : IDL.Principal,
  'trendAlerts' : IDL.Vec(IDL.Text),
  'stylePreferences' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addTrendItem' : IDL.Func([TrendItem], [], []),
  'addWardrobeItem' : IDL.Func([IDL.Principal, WardrobeItem], [], []),
  'createOrUpdateStyleProfile' : IDL.Func([StyleProfile], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPersonalizedTrends' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TrendItem)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStyleProfile' : IDL.Func([IDL.Principal], [StyleProfile], ['query']),
  'getTrendingItems' : IDL.Func([], [IDL.Vec(TrendItem)], ['query']),
  'getWardrobe' : IDL.Func([IDL.Principal], [IDL.Vec(WardrobeItem)], ['query']),
  'getWardrobeSuggestions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'removeSavedOutfit' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'removeWardrobeItem' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'saveOutfit' : IDL.Func([IDL.Principal, Outfit], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'seedTrendItems' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const TrendItem = IDL.Record({
    'trendTags' : IDL.Vec(IDL.Text),
    'productId' : IDL.Nat,
    'trendScore' : IDL.Nat,
    'dateAdded' : IDL.Int,
  });
  const WardrobeItem = IDL.Record({
    'color' : IDL.Text,
    'productId' : IDL.Opt(IDL.Nat),
    'customName' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const BodyMeasurements = IDL.Record({
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'hips' : IDL.Nat,
    'chest' : IDL.Nat,
    'waist' : IDL.Nat,
  });
  const Outfit = IDL.Record({ 'items' : IDL.Vec(IDL.Nat) });
  const StyleProfile = IDL.Record({
    'bodyMeasurements' : BodyMeasurements,
    'savedOutfits' : IDL.Vec(Outfit),
    'userId' : IDL.Principal,
    'trendAlerts' : IDL.Vec(IDL.Text),
    'stylePreferences' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addTrendItem' : IDL.Func([TrendItem], [], []),
    'addWardrobeItem' : IDL.Func([IDL.Principal, WardrobeItem], [], []),
    'createOrUpdateStyleProfile' : IDL.Func([StyleProfile], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPersonalizedTrends' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TrendItem)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStyleProfile' : IDL.Func([IDL.Principal], [StyleProfile], ['query']),
    'getTrendingItems' : IDL.Func([], [IDL.Vec(TrendItem)], ['query']),
    'getWardrobe' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WardrobeItem)],
        ['query'],
      ),
    'getWardrobeSuggestions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeSavedOutfit' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'removeWardrobeItem' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'saveOutfit' : IDL.Func([IDL.Principal, Outfit], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'seedTrendItems' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };