/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMeasurements {
  'weight' : bigint,
  'height' : bigint,
  'hips' : bigint,
  'chest' : bigint,
  'waist' : bigint,
}
export interface Outfit { 'items' : Array<bigint> }
export interface Product {
  'id' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
  'isTrending' : boolean,
}
export interface StyleProfile {
  'bodyMeasurements' : BodyMeasurements,
  'savedOutfits' : Array<Outfit>,
  'userId' : Principal,
  'trendAlerts' : Array<string>,
  'stylePreferences' : Array<string>,
}
export interface TrendItem {
  'trendTags' : Array<string>,
  'productId' : bigint,
  'trendScore' : bigint,
  'dateAdded' : bigint,
}
export interface WardrobeItem {
  'color' : string,
  'productId' : [] | [bigint],
  'customName' : [] | [string],
  'category' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'addTrendItem' : ActorMethod<[TrendItem], undefined>,
  'addWardrobeItem' : ActorMethod<[Principal, WardrobeItem], undefined>,
  'createOrUpdateStyleProfile' : ActorMethod<[StyleProfile], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getPersonalizedTrends' : ActorMethod<[Principal], Array<TrendItem>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getStyleProfile' : ActorMethod<[Principal], StyleProfile>,
  'getTrendingItems' : ActorMethod<[], Array<TrendItem>>,
  'getWardrobe' : ActorMethod<[Principal], Array<WardrobeItem>>,
  'getWardrobeSuggestions' : ActorMethod<[Principal], Array<Product>>,
  'removeSavedOutfit' : ActorMethod<[Principal, bigint], undefined>,
  'removeWardrobeItem' : ActorMethod<[Principal, bigint], undefined>,
  'saveOutfit' : ActorMethod<[Principal, Outfit], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedProducts' : ActorMethod<[], undefined>,
  'seedTrendItems' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];